### ISSUE TITLE
Program gets stuck while updating list of outdated packages

### ISSUE THREAD

**Issue by tremblerz** [upendra-k14/pip_gui#19] opened 2016-07-29 11:50 UTC
It doesn't stop nor it gets any other feature of the program to work.

**Comment by upendra-k14** [comment] 2016-07-29 11:53
@tremblerz , can you please post the terminal output. It appears that there may be some log to register this behaviour if there is some error.

**Comment by tremblerz** [comment] 2016-07-29 11:55
`python3 -m pip_tkinter`
`2016-07-29 17:04:47,197 - __main__ - INFO - Welcome today`
`2016-07-29 17:07:18,153 - __main__ - ERROR - Logging an uncaught exception in tkinter mainloop`
`Traceback (most recent call last):`
`File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/__main__.py", line 143, in __call__
    return self.func(*args)
  File "/usr/lib/python3.4/tkinter/__init__.py", line 585, in callit
    func(*args)
  File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/manage_installed_modules_page.py", line 319, in update_outdated_packages
    results_tuple = pip_list_outdated_command()
  File "/home/abhi/Downloads/CourseMaterial/python/gui/pip_gui/pip_tkinter/utils.py", line 286, in pip_list_outdated_command
    latest_version = installed_pkg_list[i].split(' - Latest: ')[1].split(' [')[0]
IndexError: list index out of range
`

**Comment by tremblerz** [comment] 2016-07-29 11:55
You can mark it as duplicate of [#17](https://github.com/upendra-k14/pip_gui/issues/17)

**Comment by upendra-k14** [comment] 2016-07-29 11:59
Marked duplicate of issue #17

**Closed as completed by upendra-k14** 2016-07-29 11:59 UTC
